#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
if [ "x`cat /etc/redhat-release | grep Enterprise`x" == "xx" ] ; then
  nohup $OPENSHIFT_REPO_DIR/bin/dart-f16 $OPENSHIFT_REPO_DIR/diy/server.dart > $OPENSHIFT_LOG_DIR/server.log 2>&1 &
else
  nohup $OPENSHIFT_REPO_DIR/bin/dart-rhel6 $OPENSHIFT_REPO_DIR/diy/server.dart > $OPENSHIFT_LOG_DIR/server.log 2>&1 &
fi