#!/bin/bash
# The logic to stop your application should be put in this script.
uname=`id -nu`
echo "Looking for dart processes run by user $uname"
kill `ps -u ${uname} | grep dart | grep -v grep | awk '{ print $1 }'` > /dev/null 2>&1
exit 0
